### ISSUE TITLE
Connect more than one ios device to OSX

### ISSUE THREAD

**Issue by artem-exd** [jensmeder/DarkLightning#10]
Hi,
great work. Is there way to connect two ios devices to OSX and recognize where is first and where is second, I need to make app bundle source synchronization between two ios devices through USB connected to OSX. 
I need to sync, video and images.
is there possible?
thank you very much.

**Comment by jensmeder** [comment]
Hi there,

yes, that should be possible already. You need to start the `JMMobileDevicePort` on both iOS devices. On OSX you need to start the `JMUSBDeviceManager` and wait for the `-(void) deviceManager:(nonnull JMUSBDeviceManager*)manager deviceDidAttach:(nonnull JMUSBDevice*)device` callback for each of the devices. As soon as a device has been attached to your Mac you just need to open a `JMUSBDeviceConnection` and connect to it. When both devices have been connected you just need to forward the incoming data from one `JMUSBDeviceConnection` to the other.

Hope that helps!

**Comment by artem-exd** [comment]
cool man Thanks for the response.
Also Is there possible to do from one ios device to second ios device without osx mediator, just connect devices through dual USB cable. Right  now I use MultipeerConnectivity framework to sync ios devices through Wifi or Bluetooth but the speed of sync is too slow. So maybe is possible to sync devices through USB without osx. Can you say your thought about that? 
Thanks, with you every success:)

**Comment by jensmeder** [comment]
Unfortunately, a direct device to device connection via Lightning/USB cable is impossible. You could downsize the whole setup to a usbmuxd server on a SoC board such as Raspberry Pi or Beaglebone. Have a look at https://github.com/davidahouse/PiTalk for more information on that.

**Comment by artem-exd** [comment]
Ok thanks that let me know. 
Also can you tell me If use mac app and two ios app for sync feature through DarkLightning, there need mfi program certification?

**Comment by jensmeder** [comment]
Nope, you do not need MFI certification for that. You might have heard about Duet Display. Same technology, no MFI.
