### ISSUE TITLE
Is there any difference in speed to PeerTalk?

### ISSUE THREAD

**Issue by kez22** [jensmeder/DarkLightning#13]

**Comment by jensmeder** [comment]
Hey!

I have not done any benchmarks but the underlying technology etc. is the same so I would be really surprised if there was any significant performance difference between PeerTalk and DarkLightning.

**Comment by kez22** [comment]
Great thanks for letting me know.  Thats what I thought.  I currently am using PeerTalk so was wondering if I should switch.
