### ISSUE TITLE
Memory leak when stopping and starting JMUSBDeviceManager

### ISSUE THREAD

**Issue by kirankunigiri** [jensmeder/DarkLightning#35]
To get around the fact that the iOS app needs to be started before the OSX App, I created a timer that runs every second and stops and starts the `JMUSBDeviceManager`. Although this solution works, the app gradually increases its memory use to the point where it freezes and crashes.

I have tried de-initializing the JMUSBDeviceManager and creating a new one, along with the `JMUSBDevice`, and disconnecting and de-initializing the `JMUSBDeviceConnection` during each restart. However, the memory use stays the same and always crashes.

Is there a better way to allow the apps to connect no matter which one is first? And is the memory problem due to how I am handling them, or is it a problem within the classes themselves?

**Comment by jensmeder** [comment]
Fixed in [2.0.0-alpha1](https://github.com/jensmeder/DarkLightning/releases/tag/2.0.0-alpha1).
