### ISSUE TITLE
Packets larger than 8192 bytes

### ISSUE THREAD

**Issue by serk1** [jensmeder/DarkLightning#4]
I'm having trouble receiving tagged packets larger than 8192 bytes on the iOS side.

I'm assuming that once a packet gets larger than that, it gets split up into smaller pieces, which should be handled by JMTaggedPacketProtocol. The problem is that my JMMobileDevicePortDelegate is only receiving one call to didReceiveData and when I send this data to processData() in my JMTaggedPacketProtocol object, it is returning an empty array.

Shouldn't my JMMobileDevicePortDelegate be receiving multiple calls to didReceiveData if the data is being split up? Then the JMTaggedPacketProtocol object would buffer the partial data until it has enough to reconstruct the packet.

Any idea what I might be doing wrong? If I send any packets with their data (NSData) less than 8192 bytes, it works fine.

**Comment by jensmeder** [comment]
Hey there!

Thanks for reporting. I will have a look at it and keep you posted. :)

**Comment by serk1** [comment]
Cool, thanks. The issue I'm having seems to be from the sender (OSX). My workaround is to split up the encoded packet using subdataWithRange() into chunks less than 8192 bytes and send each chunk separately. The receiver is doing a good job buffering and reassembling the packets.

**Comment by jensmeder** [comment]
I assume that some buffers are not being emptied right away probably some low level unix sockets. 

So the bug only occurs when you try to send 8192 bytes from OSX? Have you tried the other way around as well (8192bytes from iOS to OSX)?

**Comment by serk1** [comment]
I just tried it the other way around (iOS to OSX) and there is no problem there.

I am running OSX 10.11.3 on a 2013 Macbook Pro retina and using XCode 7.2.1 with cocoapods. The iOS device is an iPad Pro with iOS 9.2.1

**Comment by jens-meder** [comment]
Airght. Thanks for the details. I will build a test setup for it and try to reproduce it.

**Comment by jensmeder** [comment]
Alright. Thanks for the details. I will build a test setup for it and try to reproduce it.

**Comment by jens-meder** [comment]
@serk1 Sorry for the delay. I have found the cause of the bug and have just pushed a bugfix for it. Could you please verify that https://github.com/jensmeder/DarkLightning/pull/5 fixes your bug?
