### ISSUE TITLE
Connect iOS Device to Apple TV

### ISSUE THREAD

**Issue by tomgekeerd** [jensmeder/DarkLightning#43]
I tried to connect my iPhone to the Apple TV using a USB-C to lightning cable, but it wasn't working.

Would it be theoretically possible to add this to the library? I read that this library is made by using a program that runs on these devices to have an interface for iOS/tvOS device, but I question if it's possible to use this interface between these devices as well.

**Comment by jensmeder** [comment]
Hi there,

AFAIK there is no way to realize a direct connection between tvOS and iOS via USB. The system only works between macOS (or any other OS that can run the usbmuxd service) and either iOS or tvOS. The mechanism requires iOS/tvOS to be the TCP server that communicates with the usbmuxd service on macOS via USB.
